name: api.postman

on:
  workflow_dispatch:

jobs:
  smoketests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: petstore-api
        uses: matt-ball/newman-action@master
        with:
          collection: Petstore.postman_collection.json
          environment: Petstorenv.postman_environment.json

      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: testResults
