name: api.postman

on:
  workflow_dispatch:

jobs:
 smoketests:
  runs-on: ubuntu-latest
  
  steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: API Tests using Newman Action
        uses: matt-ball/newman-action@master
        with:
          collection: Petstore.postman_collection.json
          environment: Petstorenv.postman_environment.json
