name: api.postman

on:
  workflow_dispatch:

jobs:
 smoketests:
  runs-on: ubuntu-latest
  
  steps:
      - name: checkout
        uses: actions/checkout@master
      
      - name: Sourcing Private API - PROD Tests
        uses: matt-ball/newman-action@master
        with:
          collection: dealer.qa.sourcing.private.api.smoke.test.postman_collection.json
          environment: dealer.qa.sourcing.private.api.smoke.data.PROD.postman_environment.json
